
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "bento/ubuntu-16.04"
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.39"
  config.vm.network :forwarded_port, guest: 21, host: 8121
  config.vm.network :forwarded_port, guest: 23, host: 8123
  config.vm.network :forwarded_port, guest: 80, host: 8180
  config.ssh.insert_key = true

  config.vm.provider :virtualbox do |v|
    v.name = "synchronet"
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "synchronet"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install python -y
  SHELL

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :synchronet do |synchronet|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../main.yml"
    ansible.verbose = true
    ansible.host_key_checking = false
    #ansible.verbose = "vvvv"
  end

end
