---
- name: Preparations | Disable and Stop AutoUpdates
  command: "{{item}}"
  with_items:
    - systemctl stop apt-daily.service
    - systemctl disable apt-daily.service
    - systemctl stop apt-daily.timer
    - systemctl disable apt-daily.timer
  when: ansible_os_family == "Debian"

- name: Preparations Ubuntu | Installing Preliminary System Packages
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - wget
    - zip
    - unzip
    - subversion
    - cvs
    - build-essential
    - make
    - pkg-config
    - gcc
    - autotools-dev
    - libnspr4-dev
    - libncurses5-dev
    - dosemu
  async: 900
  poll: 5
  when: ansible_os_family == "Debian"

- name: Downloads Dosemu for Centos
  get_url:
    url: http://download1.rpmfusion.org/free/el/updates/6/x86_64//dosemu-1.4.0.8-15.20130205git.el6.x86_64.rpm
    dest: /tmp/
  when: ansible_os_family == "RedHat"

- name: Installs Dosemu package.
  yum:
     name: /tmp/dosemu-1.4.0.8-15.20130205git.el6.x86_64.rpm
     state: present
  when: ansible_os_family == "RedHat"

- name: Preparations Centos | Installing Preliminary System Packages
  yum: pkg={{item}} state=installed
  with_items:
    - wget
    - zip
    - unzip
    - "@Development tools"
    - cvs
    - nspr-devel
    - ncurses-devel
    - kernel-headers
    - kernel
  when: ansible_os_family == "RedHat"
