
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.3"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "synchronet"
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "synchronet"
  config.vm.network :private_network, ip: "192.168.33.2"
  config.vm.network :forwarded_port, guest: 21, host: 21
  config.vm.network :forwarded_port, guest: 23, host: 23
  config.vm.network :forwarded_port, guest: 80, host: 23

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :synchronet do |synchronet|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../main.yml"
    #ansible.inventory_path = "inventory"
    ansible.verbose = true
    ansible.sudo = true
  end

end
